import { Divider, Grid, Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import RecipeCard from "../components/RecipeCard";
import Layout from "../layouts/layout";
import axios from "axios";

export async function getServerSideProps() {
  const headersList = {
    Accept: "*/*",
    "User-Agent": "Thunder Client (https://www.thunderclient.com)",
    "X-RapidAPI-Key": "43f274a3e9mshffa5eaeb7bfffd2p14bff5jsnf825be0f2e08",
    "X-RapidAPI-Host": "tasty.p.rapidapi.com",
  };

  const reqOptions = {
    url: "https://tasty.p.rapidapi.com/recipes/list?from=0&size=10",
    method: "GET",
    headers: headersList,
  };

  const { data } = (await axios.request(reqOptions)) as any;
  return {
    props: {
      data,
    },
  };
}
const Home: NextPage = ({ data }: { data: any }) => {
  return (
    <>
      <Head>
        <title>Recipes App w/ T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading my={"8"}>Your Recipes</Heading>
        <Divider mt={"8"} />
        <Heading my={"8"}>Community Recipes</Heading>
        <Grid
          justifyItems={"center"}
          templateColumns={{
            sm: "repeat(1,1fr)",
            md: "repeat(2,1fr)",
            lg: "repeat(3,1fr)",
          }}
          gap={4}
        >
          {data.results.map((recipe: any) => (
            <RecipeCard
              key={recipe.id}
              title={recipe.name}
              description={recipe.description}
              image={recipe.thumbnail_url}
              author={recipe.credits[0].name}
            />
          ))}
        </Grid>
      </Layout>
    </>
  );
};

export default Home;
