import { Container } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import Header from "../components/Header";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <title>Recipes App w/ T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW={"container.xl"} p={6}>
        <Header />
        {children}
      </Container>
    </>
  );
}
